### ISSUE TITLE
Property View Script Components

### ISSUE THREAD

**Issue by antonallote** [SradnickDev/Photon-Misc#1]
Hey sadly it does'nt work for me. I've been importing the prefab and assigned the view and content field... but apparently it does'nt show anything except of the text set per default in the textfield;

I am using Unity version 2020.1.7f1 and obviously PUN on osx. 
I would be happy if u could drop me a line. 

Greets :)

**Comment by SradnickDev** [comment]
Any errors? Did u pressed “-“ to toggle it ? I mean its rly simple, it is just writing everything to a text.
